#! /bin/sh

ls -1 ~/ferlatte@gmail.com\ -\ Google\ Drive/My\ Drive/Projects
ls -1 ~/mark@truss.works\ -\ Google\ Drive/My\ Drive/Projects
ls -1 ~/mark@truss.works\ -\ Google\ Drive/My\ Drive/Truss-Users-mark/Projects
