#! /bin/sh

ls ~/ferlatte@gmail.com\ -\ Google\ Drive/My\ Drive/Projects
ls ~/mark@truss.works\ -\ Google\ Drive/My\ Drive/Projects
ls ~/mark@truss.works\ -\ Google\ Drive/My\ Drive/Truss-Users-mark/Projects 

